version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - pwd
      - ls -la
      - cd Backend/SpringBootDeploymentCICD/MODULE8/8.4/AWScodePipelineAndGithubHooks/testing-app
      - pwd
      - ls -la
      - mvn -v

  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  base-directory: Backend/SpringBootDeploymentCICD/MODULE8/8.4/AWScodePipelineAndGithubHooks/testing-app/target
  files:
    - '*.jar'




