version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - pwd
      - ls -la
      - mvn -v

  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - '/root/.m2/**/*'


