spring:
  application:
    name: order-service


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
#    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  port: 8081
  servlet:
    context-path: /orders


eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 100ms

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 1s
        limitForPeriod: 100
        timeoutDuration: 10ms