spring:
  ai:
    model:
      chat: openai
      embedding: none
      image: none
      moderation: none
      audio:
        speech: none
        transcription: none

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.9