spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO
    com.example.weatherAPI: INFO

server:
  port: 8081
  shutdown: graceful
