spring:
  application:
    name: weatherAPI

management:
  endpoints:
    web:
      exposure:
        include: "*"

weather:
  geocoding:
    base-url: https://geocoding-api.open-meteo.com/v1

  api:
    base-url: https://api.open-meteo.com/v1