spring:
  application:
    name: weatherAPI

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
#      ssl:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

weather:
  geocoding:
    base-url: https://geocoding-api.open-meteo.com/v1

  api:
    base-url: https://api.open-meteo.com/v1

logging:
  level:
    org.springframework: DEBUG